### ISSUE TITLE
No way to do equivalent of a "Full Outer" join?

### ISSUE THREAD

**Issue by adyork** [BCODMO/frictionless-usecases#12]
The way pipelines/dataflows architectured joins is pretty inflexible compared with join tools we were familiar with due to the "source" "target" logic and inability to achieve a full outer join.

This is my summary of the core of the issue as best I can tell. Please let me know if there is an existing join configuration other method I am missing here.

What we really want is the join types available in any other join utility I have ever used (e.g. sql, pandas, tableau, etc) with join types:

![image](https://user-images.githubusercontent.com/9537357/56821182-abf6e180-681b-11e9-8a48-d284016847f1.png)
![image](https://user-images.githubusercontent.com/9537357/56821125-8a95f580-681b-11e9-87dc-c85d509b83dc.png)
![image](https://user-images.githubusercontent.com/9537357/56821189-aef1d200-681b-11e9-84c6-49c2367c93f1.png)
![image](https://user-images.githubusercontent.com/9537357/56821192-b1542c00-681b-11e9-93db-3fdd40097975.png)
https://www.w3schools.com/sql/sql_join.asp

pipelines/dataflows has a Full: True|False option which from what I can tell gets us "inner", and "right"  joins.

Left is impossible in the target/source model, but that isn't a big limitation since we can achieve the same results and with being careful about what we call the "source" and "target."  Though I have run into workflow issue with the order dependency in general, see #11.

The biggest issue I can see is that I can't do a full outer join (meaning return all rows from either source regardless of whether there was a match).

Here is an example of why we want full outer.

You have a dataset with bottle samples and nutrients (resource: nutrients).  You have an event log with the bottle_ids that you can join to get lat/lon/depth columns into your nutrient data.

In a perfect world, all bottle IDs would be in the event log data.  In reality often what you are using as keys might have issues that cause no match in the "source."

Perfect world: All bottle_ids in nutrients data are also in event log
* Join with Full:T|F would give you what you want, lat/lon/depth for every row in your nutrient data.

Reality:  Missing key values in event log, or mismatches between key values (e.g. "statin 12" vs "station 12" or "12_a" vs "12a."
* Join with Full: True = You get blank values for lat|lon|depth columns where no match in event log.
* Join with Full: False = You get any unmatched rows dropped from dataset.

If we could do full outer join we could easily see where there are no matches in either data resource. With the existing join options you loose any unmatched values in the key of the event log (source) so can't tell what is going on, whether it is inconsistent naming, misspelling, or just missing values

**Comment by adyork** [comment]
@BCODMO/frictionlessdata-pilot-project, does this make sense to you?  Am I missing a way to configure join step to do the equivalent of "outer?"

The above example is just one case we would want outer for catching errors in the key, but there are plenty of times you just need to do an outer join, not just for catching errors.

**Comment by adyork** [comment]
I added a new usecase which would need a full outer join.  Hopefully this clarifies one need I described above.
This is a complicated one, but skip to the notes in the README for data version 2, processing needs:
https://github.com/BCODMO/frictionless-usecases/blob/master/usecases/water_column_particle_profiles/README.md#data-version-2

**Comment by roll** [comment]
The implementation at a review. To test it now:
```
pip install --upgrade git+https://github.com/roll/dataflows.git@full-outer-join
pip install --upgrade git+https://github.com/okfn/datapackage-pipelines.git@full-outer-join
```
E.g.
```yml
join:
  title: join
  description: "test join"
  pipeline:

  - run: load
    parameters:
      from: 'population.csv'
      name: population
      format: csv

  - run: load
    parameters:
      from: 'cities.csv'
      name: cities
      format: csv

  - run: join
    parameters:
      mode: full-outer
      source:
        name: population
        key: [id]
      target:
        name: cities
        key: [id]
      fields:
        population:
          name: population

  - run: dump.to_path
    parameters:
      resources: [cities]
      out-path: 'output'
      pretty-descriptor: true
```
cc @cschloer
