### ISSUE TITLE
Regex option for the `delete_fields` processor

### ISSUE THREAD

**Issue by roll** [BCODMO/frictionless-usecases#16]
# Overivew

See https://github.com/BCODMO/frictionless-usecases/issues/9#issuecomment-498218348

**Comment by roll** [comment]
@adyork 
@cschloer 
It's done

```bash
pip install --upgrade datapackage-pipelines==2.1.9
```

```yml
regex_delete:
  title: test
  description: "test regex option for delete_fields"
  pipeline:

  - run: load
    parameters:
      from: 'regex.csv'
      name: data
      format: csv

  - run: delete_fields
    parameters:
        resources: data
        regex: false
        fields: [temperature (24h)]

  - run: dump.to_path
    parameters:
      resources: [data]
      out-path: 'output'
      pretty-descriptor: true
```
