### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#37]
Hey,

We've run into this problem a few times but this is the easiest reproducable version. It seems like if too many flows are added to the Flow function call it runs into an error.

csv:
```
col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22,col23,col24,col25,col26,col27,col28,col29,col30,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40,col41,col42,col43,col44,col45,col46,col47,col48,col49,col50,col51,col52,col53,col54,col55,col56,col57,col58,col59,col60,col61,col62,col63,col64,col65,col66,col67,col68,col69,col70,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80,col81,col82,col83,col84,col85,col86,col87,col88,col89,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99,col100,col101,col102,col103,col104,col105,col106,col107,col108,col109,col110,col111,col112,col113,col114,col115,col116,col117,col118,col119,col120,col121,col122,col123,col124,col125,col126,col127,col128,col129,col130,col131,col132,col133,col134,col135,col136,col137,col138,col139,col140,col141,col142,col143,col144,col145,col146,col147,col148,col149,col150,col151,col152,col153,col154,col155,col156,col157,col158,col159,col160,col161,col162,col163,col164,col165,col166,col167,col168,col169,col170,col171,col172,col173,col174,col175,col176,col177,col178,col179,col180,col181,col182,col183,col184,col185,col186,col187,col188,col189,col190,col191,col192,col193,col194,col195,col196,col197,col198,col199,col200,col201,col202,col203,col204,col205,col206,col207,col208,col209,col210,col211,col212,col213,col214,col215,col216,col217,col218,col219,col220,col221,col222,col223,col224,col225,col226,col227,col228,col229,col230,col231,col232,col233,col234,col235,col236,col237,col238,col239,col240,col241,col242,col243,col244,col245,col246,col247,col248,col249,col250,col251,col252,col253,col254,col255,col256,col257,col258,col259,col260,col261,col262,col263,col264,col265,col266,col267,col268,col269,col270,col271,col272,col273,col274,col275,col276,col277,col278,col279,col280,col281,col282,col283,col284,col285,col286,col287,col288,col289,col290,col291,col292,col293,col294,col295,col296,col297,col298,col299,col300,col301,col302,col303,col304,col305,col306,col307,col308,col309,col310,col311,col312,col313,col314,col315,col316,col317,col318,col319,col320,col321,col322,col323,col324,col325,col326,col327,col328,col329,col330,col331,col332,col333,col334,col335,col336,col337,col338,col339,col340,col341,col342,col343,col344,col345,col346,col347,col348,col349,col350,col351,col352,col353,col354,col355,col356,col357,col358,col359,col360,col361,col362,col363,col364,col365,col366,col367,col368,col369,col370,col371,col372,col373,col374,col375,col376,col377,col378,col379,col380,col381,col382,col383,col384,col385,col386,col387,col388,col389,col390,col391,col392,col393,col394,col395,col396,col397,col398,col399
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
```

pipeline-spec.yaml:
```
max-recursion-depth:
  title: max recursion depth
  description: ''
  version: v1.0.7
  pipeline:
  - run: load
    parameters:
      format: csv
      from: /home/conrad/Projects/whoi/datasets/misc/test_recursion.csv
      headers: 1
      infer_strategy: strings
      cast_strategy: strings
      override_schema:
        missingValues:
        - ''
        - nd
  - run: set_types
    cache: true
    parameters:
      regex: false
      resources:
      - res1
      types:
        col0:
          type: number
        col1:
          type: number
        col2:
          type: number
        col3:
          type: number
        col4:
          type: number
        col5:
          type: number
        col6:
          type: number
        col7:
          type: number
        col8:
          type: number
        col9:
          type: number
        col10:
          type: number
        col11:
          type: number
        col12:
          type: number
        col13:
          type: number
        col14:
          type: number
        col15:
          type: number
        col16:
          type: number
        col17:
          type: number
        col18:
          type: number
        col19:
          type: number
        col20:
          type: number
        col21:
          type: number
        col22:
          type: number
        col23:
          type: number
        col24:
          type: number
        col25:
          type: number
        col26:
          type: number
        col27:
          type: number
        col28:
          type: number
        col29:
          type: number
        col30:
          type: number
        col31:
          type: number
        col32:
          type: number
        col33:
          type: number
        col34:
          type: number
        col35:
          type: number
        col36:
          type: number
        col37:
          type: number
        col38:
          type: number
        col39:
          type: number
        col40:
          type: number
        col41:
          type: number
        col42:
          type: number
        col43:
          type: number
        col44:
          type: number
        col45:
          type: number
        col46:
          type: number
        col47:
          type: number
        col48:
          type: number
        col49:
          type: number
        col50:
          type: number
        col51:
          type: number
        col52:
          type: number
        col53:
          type: number
        col54:
          type: number
        col55:
          type: number
        col56:
          type: number
        col57:
          type: number
        col58:
          type: number
        col59:
          type: number
        col60:
          type: number
        col61:
          type: number
        col62:
          type: number
        col63:
          type: number
        col64:
          type: number
        col65:
          type: number
        col66:
          type: number
        col67:
          type: number
        col68:
          type: number
        col69:
          type: number
        col70:
          type: number
        col71:
          type: number
        col72:
          type: number
        col73:
          type: number
        col74:
          type: number
        col75:
          type: number
        col76:
          type: number
        col77:
          type: number
        col78:
          type: number
        col79:
          type: number
        col80:
          type: number
        col81:
          type: number
        col82:
          type: number
        col83:
          type: number
        col84:
          type: number
        col85:
          type: number
        col86:
          type: number
        col87:
          type: number
        col88:
          type: number
        col89:
          type: number
        col90:
          type: number
        col91:
          type: number
        col92:
          type: number
        col93:
          type: number
        col94:
          type: number
        col95:
          type: number
        col96:
          type: number
        col97:
          type: number
        col98:
          type: number
        col99:
          type: number
        col100:
          type: number
        col101:
          type: number
        col102:
          type: number
        col103:
          type: number
        col104:
          type: number
        col105:
          type: number
        col106:
          type: number
        col107:
          type: number
        col108:
          type: number
        col109:
          type: number
        col110:
          type: number
        col111:
          type: number
        col112:
          type: number
        col113:
          type: number
        col114:
          type: number
        col115:
          type: number
        col116:
          type: number
        col117:
          type: number
        col118:
          type: number
        col119:
          type: number
        col120:
          type: number
        col121:
          type: number
        col122:
          type: number
        col123:
          type: number
        col124:
          type: number
        col125:
          type: number
        col126:
          type: number
        col127:
          type: number
        col128:
          type: number
        col129:
          type: number
        col130:
          type: number
        col131:
          type: number
        col132:
          type: number
        col133:
          type: number
        col134:
          type: number
        col135:
          type: number
        col136:
          type: number
        col137:
          type: number
        col138:
          type: number
        col139:
          type: number
        col140:
          type: number
        col141:
          type: number
        col142:
          type: number
        col143:
          type: number
        col144:
          type: number
        col145:
          type: number
        col146:
          type: number
        col147:
          type: number
        col148:
          type: number
        col149:
          type: number
        col150:
          type: number
        col151:
          type: number
        col152:
          type: number
        col153:
          type: number
        col154:
          type: number
        col155:
          type: number
        col156:
          type: number
        col157:
          type: number
        col158:
          type: number
        col159:
          type: number
        col160:
          type: number
        col161:
          type: number
        col162:
          type: number
        col163:
          type: number
        col164:
          type: number
        col165:
          type: number
        col166:
          type: number
        col167:
          type: number
        col168:
          type: number
        col169:
          type: number
        col170:
          type: number
        col171:
          type: number
        col172:
          type: number
        col173:
          type: number
        col174:
          type: number
        col175:
          type: number
        col176:
          type: number
        col177:
          type: number
        col178:
          type: number
        col179:
          type: number
        col180:
          type: number
        col181:
          type: number
        col182:
          type: number
        col183:
          type: number
        col184:
          type: number
        col185:
          type: number
        col186:
          type: number
        col187:
          type: number
        col188:
          type: number
        col189:
          type: number
        col190:
          type: number
        col191:
          type: number
        col192:
          type: number
        col193:
          type: number
        col194:
          type: number
        col195:
          type: number
        col196:
          type: number
        col197:
          type: number
        col198:
          type: number
        col199:
          type: number
        col200:
          type: number
        col201:
          type: number
        col202:
          type: number
        col203:
          type: number
        col204:
          type: number
        col205:
          type: number
        col206:
          type: number
        col207:
          type: number
        col208:
          type: number
        col209:
          type: number
        col210:
          type: number
        col211:
          type: number
        col212:
          type: number
        col213:
          type: number
        col214:
          type: number
        col215:
          type: number
        col216:
          type: number
        col217:
          type: number
        col218:
          type: number
        col219:
          type: number
        col220:
          type: number
        col221:
          type: number
        col222:
          type: number
        col223:
          type: number
        col224:
          type: number
        col225:
          type: number
        col226:
          type: number
        col227:
          type: number
        col228:
          type: number
        col229:
          type: number
        col230:
          type: number
        col231:
          type: number
        col232:
          type: number
        col233:
          type: number
        col234:
          type: number
        col235:
          type: number
        col236:
          type: number
        col237:
          type: number
        col238:
          type: number
        col239:
          type: number
        col240:
          type: number
        col241:
          type: number
        col242:
          type: number
        col243:
          type: number
        col244:
          type: number
        col245:
          type: number
        col246:
          type: number
        col247:
          type: number
        col248:
          type: number
        col249:
          type: number
        col250:
          type: number
        col251:
          type: number
        col252:
          type: number
        col253:
          type: number
        col254:
          type: number
        col255:
          type: number
        col256:
          type: number
        col257:
          type: number
        col258:
          type: number
        col259:
          type: number
        col260:
          type: number
        col261:
          type: number
        col262:
          type: number
        col263:
          type: number
        col264:
          type: number
        col265:
          type: number
        col266:
          type: number
        col267:
          type: number
        col268:
          type: number
        col269:
          type: number
        col270:
          type: number
        col271:
          type: number
        col272:
          type: number
        col273:
          type: number
        col274:
          type: number
        col275:
          type: number
        col276:
          type: number
        col277:
          type: number
        col278:
          type: number
        col279:
          type: number
        col280:
          type: number
        col281:
          type: number
        col282:
          type: number
        col283:
          type: number
        col284:
          type: number
        col285:
          type: number
        col286:
          type: number
        col287:
          type: number
        col288:
          type: number
        col289:
          type: number
        col290:
          type: number
        col291:
          type: number
        col292:
          type: number
        col293:
          type: number
        col294:
          type: number
        col295:
          type: number
        col296:
          type: number
        col297:
          type: number
        col298:
          type: number
        col299:
          type: number
        col300:
          type: number
        col301:
          type: number
        col302:
          type: number
        col303:
          type: number
        col304:
          type: number
        col305:
          type: number
        col306:
          type: number
        col307:
          type: number
        col308:
          type: number
        col309:
          type: number
        col310:
          type: number
        col311:
          type: number
        col312:
          type: number
        col313:
          type: number
        col314:
          type: number
        col315:
          type: number
        col316:
          type: number
        col317:
          type: number
        col318:
          type: number
        col319:
          type: number
        col320:
          type: number
        col321:
          type: number
        col322:
          type: number
        col323:
          type: number
        col324:
          type: number
        col325:
          type: number
        col326:
          type: number
        col327:
          type: number
        col328:
          type: number
        col329:
          type: number
        col330:
          type: number
        col331:
          type: number
        col332:
          type: number
        col333:
          type: number
        col334:
          type: number
        col335:
          type: number
        col336:
          type: number
        col337:
          type: number
        col338:
          type: number
        col339:
          type: number
        col340:
          type: number
        col341:
          type: number
        col342:
          type: number
        col343:
          type: number
        col344:
          type: number
        col345:
          type: number
        col346:
          type: number
        col347:
          type: number
        col348:
          type: number
        col349:
          type: number
        col350:
          type: number
        col351:
          type: number
        col352:
          type: number
        col353:
          type: number
        col354:
          type: number
        col355:
          type: number
        col356:
          type: number
        col357:
          type: number
        col358:
          type: number
        col359:
          type: number
        col360:
          type: number
        col361:
          type: number
        col362:
          type: number
        col363:
          type: number
        col364:
          type: number
        col365:
          type: number
        col366:
          type: number
        col367:
          type: number
        col368:
          type: number
        col369:
          type: number
        col370:
          type: number
        col371:
          type: number
        col372:
          type: number
        col373:
          type: number
        col374:
          type: number
        col375:
          type: number
        col376:
          type: number
        col377:
          type: number
        col378:
          type: number
        col379:
          type: number
        col380:
          type: number
        col381:
          type: number
        col382:
          type: number
        col383:
          type: number
        col384:
          type: number
        col385:
          type: number
        col386:
          type: number
        col387:
          type: number
        col388:
          type: number
        col389:
          type: number
        col390:
          type: number
        col391:
          type: number
        col392:
          type: number
        col393:
          type: number
        col394:
          type: number
        col395:
          type: number
        col396:
          type: number
        col397:
          type: number
        col398:
          type: number
        col399:
          type: number
```

This seems to happen because of this line in the datapackage_pipelines set types:
![Screenshot from 2020-01-08 16-28-12](https://user-images.githubusercontent.com/7134143/71990568-e7173480-3233-11ea-93f3-125481a09b8b.png)

This also occurs for us in situations where we load a ton of datasets in at a time using a comma seperated string in the `from` parameter of load (this is part of our custom load processor).

Is there a way that the Flow function can be restructured so as not to use recursion?

**Comment by akariv** [comment]
Just out of curiosity, why not do:

```
- run: set_types
    cache: true
    parameters:
      regex: false
      resources:
      - res1
      types:
        co[0-9]+:
          type: number
```
