### ISSUE TITLE
Inconcistent behavior between concatenate and load

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#4]
Concatenate has an option called `path` within the `target` key. This updates the path in the datapackage for the file. Whenever a dump_to_path step is run, resources are dumped based on that path value within the datapackage. As stated in the [documentation](https://github.com/frictionlessdata/datapackage-pipelines#concatenate), 'If omitted, the target resource will receive the name concat and will be saved at data/concat.csv in the datapackage.'. 

The new load standard processor has no parameter that allows you to set the path (or at least no documented or easily guessed parameter). Furthermore the path defaults to `${RES_NAME}.${EXT}`, which is different from the default behavior of concatenate (`data/concat.csv`).

This is similar to the https://github.com/BCODMO/frictionless-usecases/issues/3 issue because this functionality used to exist in the previous `add_resource`, `stream_remote_resources` paradigm but no longer works with load. The now deprecated `add_resource` process used to have a `path` parameter` and the default path when left empty was `data/${RES_NAME}.${EXT}`.

This is a problem because there is a parameter in the datapackage that is only accessible by concatenating resources together. Furthermore, if you don't know to overwrite the default values, the resources created by concatenate will be saved in different locations than resources created by load.

The following is a pipeline-spec.yaml file that, when run, demonstrates that the concatenated resource is saved in a different place.
```
test:
  title: test
  description: Display discrepancies between concat and load
  pipeline:
  - parameters:
      force_strings: true
      format: csv
      from: http://datadocs.bco-dmo.org/docs/TestProject/data_docs/CTD.csv
      headers: 1
      name: ctd
      skip_rows: []
    run: load
  - parameters:
      force_strings: true
      format: csv
      from: http://datadocs.bco-dmo.org/docs/TestProject/data_docs/CTD.csv
      headers: 1
      name: ctd2
      skip_rows: []
    run: load
  - parameters:
      fields:
        Date: []
        Time: []
        chlorophylla: []
        cond_and_temp: []
        cond_and_temp_str: []
        conductivity: []
        dissolvedosaturation: []
        lat: []
        lon: []
        newTemperature: []
        pressure: []
        salinity: []
        scan: []
        temperature: []
      sources: [ctd]
      target: {name: ctd_new}
    run: concatenate
  - parameters: {out-path: $TEST_PATH/results}
    run: dump_to_path
```

This is a low priority because I already updated our python library to handle data regardless of where it is saved.
