### ISSUE TITLE
limit-rows parameter in load

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#7]
limit-rows parameter was part of stream_remote_resources. Now that we use `load` instead of `add_resource` and `stream_remote_resources` there is no longer a way to limit the number of rows being streamed (no `limit-rows` parameter). This is a major issue when streaming large datasets.

**Comment by adyork** [comment]
This issue is mentioned in #8

**Comment by adyork** [comment]
@BCODMO/frictionlessdata-pilot-project what are your thoughts about this?  Are you planning on adding back some way to limit rows to load?  Is there some other way you suggest doing that?

**Comment by roll** [comment]
@cschloer 
@adyork 
Hi, now `processors.load` supports the `limit_rows` parameter e.g.:
```
  - run: load
    parameters:
      from: 'temp.csv'
      name: 'temp'
      format: csv
      limit_rows: 100
```
We need to upgrade `dataflows` to get version `0.0.53`:
```
pip install --upgrade dataflows
```
