### ISSUE TITLE
Inconsistent behavior between concatenate and load

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#8]
Concatenate has an option called `path` within the `target` key. This updates the path in the datapackage for the file. Whenever a dump_to_path step is run, resources are dumped based on that path value within the datapackage. As stated in the [documentation](https://github.com/frictionlessdata/datapackage-pipelines#concatenate), 'If omitted, the target resource will receive the name concat and will be saved at data/concat.csv in the datapackage.'. 

The new load standard processor has no parameter that allows you to set the path (or at least no documented or easily guessed parameter). Furthermore the path defaults to `${RES_NAME}.${EXT}`, which is different from the default behavior of concatenate (`data/concat.csv`).

This is similar to the https://github.com/BCODMO/frictionless-usecases/issues/7 issue because this functionality used to exist in the previous `add_resource`, `stream_remote_resources` paradigm but no longer works with load. The now deprecated `add_resource` process used to have a `path` parameter` and the default path when left empty was `data/${RES_NAME}.${EXT}`.

This is a problem because there is a parameter in the datapackage that is only accessible by concatenating resources together. Furthermore, if you don't know to overwrite the default values, the resources created by concatenate will be saved in different locations than resources created by load.

The following is a pipeline-spec.yaml file that, when run, demonstrates that the concatenated resource is saved in a different place.
```
test:
  title: test
  description: Display discrepancies between concat and load
  pipeline:
  - parameters:
      force_strings: true
      format: csv
      from: https://raw.githubusercontent.com/BCODMO/frictionless-usecases/master/usecases/746395_PierCTD/orig/SantaMonicaPier_April_2018_CTD_data.csv
      headers: 1
      name: ctd
      skip_rows: []
    run: load
  - parameters:
      force_strings: true
      format: csv
      from: https://raw.githubusercontent.com/BCODMO/frictionless-usecases/master/usecases/746395_PierCTD/orig/SantaMonicaPier_April_2018_CTD_data.csv
      headers: 1
      name: ctd2
      skip_rows: []
    run: load
  - parameters:
      fields:
        Date: []
        Time: []
        chlorophylla: []
        cond_and_temp: []
        cond_and_temp_str: []
        conductivity: []
        dissolvedosaturation: []
        lat: []
        lon: []
        newTemperature: []
        pressure: []
        salinity: []
        scan: []
        temperature: []
      sources: [ctd]
      target: {name: ctd_new}
    run: concatenate
  - parameters: {out-path: $TEST_PATH/results}
    run: dump_to_path
```

This is a low priority because I already updated our python library to handle data regardless of where it is saved.

**Comment by roll** [comment]
@cschloer 
Hi, not sure I fully understand. Is it general to setting a resource's path or only related to the `concatenate` processor?

If it's the first one than we can propose a DPP processor like this (already written for `dataflows`):
```python
from dataflows import Flow, update_resource
from datapackage_pipelines.wrapper import ingest
from datapackage_pipelines.utilities.flow_utils import spew_flow


def flow(parameters):
    return Flow(
        update_resource(**parameters),
    )


if __name__ == '__main__':
    with ingest() as ctx:
        spew_flow(flow(ctx.parameters), ctx)
```

to use it like `package_update`:

```yml
path:
  title: path
  description: "path join"
  pipeline:

  - run: load
    parameters:
      from: 'cities.csv'
      name: cities
      format: csv

  - run: processors.update_resource
    parameters:
      resources: [cities]
      path: new_path.csv

  - run: dump.to_path
    parameters:
      resources: [cities]
      out-path: 'output'
      pretty-descriptor: true
```

Is it what we need?

**Comment by cschloer** [comment]
It's somewhat a combination of both. #1 (changing the path) is probably more important, so at least there is a way to get around it. But I also think #2 (the fact that concatenate is different from load) seems counter intuitive and confusing.

But adding the update_resource into the datapackage_pipelines repo would be great! We discussed that on the call yesterday also.

**Comment by roll** [comment]
The `update_resource` processor is added to the core.

```bash
$ pip install --upgrade datapackage-pipelines==2.1.9
```

```yml

update_resource:
  title: test
  description: "test update resource processor"
  pipeline:

  - run: load
    parameters:
      from: 'cities.csv'
      name: data
      format: csv

  - run: update_resource
    parameters:
        resources: data
        metadata:
          title: New Title

  - run: dump.to_path
    parameters:
      resources: [data]
      out-path: 'output'
      pretty-descriptor: true
```
